### ISSUE TITLE
followed instructions, but not luck iOS iPhone 6s

### ISSUE THREAD

**Issue by picomatic** [goloveychuk/ZeroMQ#1]
ld: warning: ignoring file /usr/local/lib/libzmq.dylib, file was built for x86_64 which is not the architecture being linked (arm64): /usr/local/lib/libzmq.dylib

**Comment by paulofaria** [comment]
Yeah, it doesn't work on iOS yet. libzmq has to be compiled for iOS. There were some attempts before. But I guess they're outdated. For now SwiftZMQ only supports OS X. But maybe later it will support iOS. I'll also port [nanomsg](https://github.com/nanomsg/nanomsg), which is a new approach from the same author. Maybe its easier to compile nanomsg for iOS.
