### ISSUE TITLE
Readme not up to date

### ISSUE THREAD

**Issue by Dev1an** [goloveychuk/ZeroMQ#8]
The [readme](https://github.com/Zewo/ZeroMQ/blob/2e26127f4172e7624ee8a7c52cfdedb7384aa52e/README.md#embedded-framework) states

> Open the new SwiftZMQ folder, and drag the SwiftZMQ.xcodeproj into the Project Navigator of your application's Xcode project.

But there is no `SwiftZMQ.xcodeproj` file in this repository.

**Comment by goloveychuk** [comment]
@Dev1an are you using swift-package-manager and last toolchain?

**Comment by Dev1an** [comment]
No I just did `git submodule add https://github.com/Zewo/SwiftZMQ.git` as it is written in the manual

**Comment by goloveychuk** [comment]
@Dev1an sorry for old readme. We're only supporting SPM and latest snapshot.
Solutions:
1) You can pull later version, with xcodeproj. 
This e.g. https://github.com/Zewo/ZeroMQ/tree/13c7ae025aec40b3a820a569b9d43a06a6dd2bed
2) You can create xcodeproj by your own
3) you can install latest swift, latest spm, use this swift-build patch https://github.com/Zewo/swift-package-manager/releases , for generating swift project
This is until swift community merge this PR https://github.com/apple/swift-package-manager/pull/235

**Comment by Dev1an** [comment]
OK Thanks for the clarification @goloveychuk
